name: publish
run-name: Publish ${{ inputs.version }}
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: lts/*
      - run: npm ci
        name: Install
      - run: npm run build
        name: Build
      - uses: trmcnvn/chrome-addon@v2
        name: Chrome publish
        with:
          extension: iecgbpoggpmlohjeojnjjihabobaaeek
          zip: build/chrome-extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      - uses: trmcnvn/firefox-addon@v1
        name: Firefox publish
        with:
          uuid: roman@lerchster.dev
          xpi: build/firefox-extension.zip
          manifest: build/firefox-manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
