name: publish
run-name: Publish ${{ inputs.version }}

on:
  release:
    types: [released]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: lts/*
      - run: npm ci
        name: Install
      - run: npm run build
        name: Build
      - uses: actions/upload-artifact@v4
        with:
          name: extensions
          path: build/

  publish-chrome:
    name: Chrome publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extensions
          path: .
      - uses: trmcnvn/chrome-addon@v2
        with:
          extension: iecgbpoggpmlohjeojnjjihabobaaeek
          zip: chrome-extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

  publish-firefox:
    name: Firefox publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: extensions
          path: .
      - run: ls .
        name: Firefox publish
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: roman@lerchster.dev
          xpi: firefox-extension.zip
          manifest: firefox-manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
